apiVersion: v1
data:
  cacert: Cg==
  clouds.yaml: #REDACTED BASE64 ENCODE
kind: Secret
metadata:
  labels:
    clusterctl.cluster.x-k8s.io/move: "true"
  name: febri4n-ngetest-capi-cloud-config
  namespace: default
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: febri4n-ngetest-capi-md-0
  namespace: default
spec:
  template:
    spec:
      files: []
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            cloud-provider: external
            provider-id: openstack:///'{{ instance_id }}'
          name: '{{ local_hostname }}'
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: febri4n-ngetest-capi
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    serviceDomain: cluster.local
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: febri4n-ngetest-capi-control-plane
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: OpenStackCluster
    name: febri4n-ngetest-capi
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  name: febri4n-ngetest-capi-md-0
  namespace: default
spec:
  clusterName: febri4n-ngetest-capi
  replicas: 1
  selector:
    matchLabels: null
  template:
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: febri4n-ngetest-capi-md-0
      clusterName: febri4n-ngetest-capi
      failureDomain: AZ_Public01_JBBK
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: OpenStackMachineTemplate
        name: febri4n-ngetest-capi-md-0
      version: v1.30.2
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: febri4n-ngetest-capi-control-plane
  namespace: default
spec:
  kubeadmConfigSpec:
    clusterConfiguration:
      apiServer:
        extraArgs:
          cloud-provider: external
      controllerManager:
        extraArgs:
          cloud-provider: external
    files: []
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///'{{ instance_id }}'
        name: '{{ local_hostname }}'
    joinConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          cloud-provider: external
          provider-id: openstack:///'{{ instance_id }}'
        name: '{{ local_hostname }}'
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: OpenStackMachineTemplate
      name: febri4n-ngetest-capi-control-plane
  replicas: 1
  version: v1.30.2
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackCluster
metadata:
  name: febri4n-ngetest-capi
  namespace: default
spec:
  controlPlaneAvailabilityZones:
    - AZ_Public01_JBBK
  apiServerLoadBalancer:
    enabled: true
  externalNetwork:
    id: f9881508-7de0-488e-a4ff-c437f4c8687f
  identityRef:
    cloudName: openstack
    name: febri4n-ngetest-capi-cloud-config
  managedSecurityGroups:
    allNodesSecurityGroupRules:
    - description: Created by cluster-api-provider-openstack - BGP (calico)
      direction: ingress
      etherType: IPv4
      name: BGP (Calico)
      portRangeMax: 179
      portRangeMin: 179
      protocol: tcp
      remoteManagedGroups:
      - controlplane
      - worker
    - description: Created by cluster-api-provider-openstack - IP-in-IP (calico)
      direction: ingress
      etherType: IPv4
      name: IP-in-IP (calico)
      protocol: "4"
      remoteManagedGroups:
      - controlplane
      - worker
  managedSubnets:
  - cidr: 10.6.0.0/24
    dnsNameservers:
    - 8.8.8.8
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: febri4n-ngetest-capi-control-plane
  namespace: default
spec:
  template:
    spec:
      flavor: GP.2C4G-intel
      image:
        filter:
          name: capi-ubuntu-2204-kube-v1.30.2
      sshKeyName: febri4n
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: OpenStackMachineTemplate
metadata:
  name: febri4n-ngetest-capi-md-0
  namespace: default
spec:
  template:
    spec:
      flavor: GP.2C4G-intel
      image:
        filter:
          name: capi-ubuntu-2204-kube-v1.30.2
      sshKeyName: febri4n